### ISSUE TITLE
Buy Now button does not show clear guidance when user does not have a sSCRT VK

### ISSUE THREAD

**Issue by scarylooking** [SecretChainGirl-Foundation/stashh-QA#112]
Precondition: have a wallet without a sSCRT VK
Precondition: have both SCRT and sSCRT in your wallet

## Steps to reproduce
1. Open the asset page for an on-sale NFT
2. Buy now button is disabled. Hover over it.
3. Message says "Not enough sSCRT balance"

## Issue:
The problem is that I do not have a viewing key, not that my balance is low, and it is not clear from the message that this is what the problem is.

![image](https://user-images.githubusercontent.com/16178367/138573733-b827d91b-b355-489b-8d93-49bee19b93d1.png)

As a new user I would have no idea what I need to do in order to fix the problem.

## Expected:
Clearer messaging explaining that I need a viewing key, and guidance through the process.

## Note(s):
It might be OK at this stage to enable the buy now button, and to allow the transaction to fail in Keplr. This way the user isn't forced into generating a viewing key.

An alternative would be to make creating a sSCRT VK part of the Swapper process.

**Comment by lauraweindorf** [comment]
Verified :tada:

It now displays a message on hover to click the "View Balance" 

![image](https://user-images.githubusercontent.com/436905/142784593-ca017e4b-55a7-4d57-86b7-03d73b6c920e.png)

and the cursor is changed to an icon indicating that. 
![image](https://user-images.githubusercontent.com/436905/142784637-11591983-4709-48d6-9faa-9dce2c866e9d.png)

After adding sSCRT to Keplr it then shows the message:

![image](https://user-images.githubusercontent.com/436905/142784739-4cfff81a-66e3-44a8-a56b-e292deecc3ee.png)
