### ISSUE TITLE
Price Breakdown shows royalties deducted when creating a new NFT

### ISSUE THREAD

**Issue by scarylooking** [SecretChainGirl-Foundation/stashh-QA#119]
## Steps to reproduce
1. Go through the Create NFT flow
2. Check Sell this NFT
3. Enter 25% for Royalties and 100 sSCRT as the price

## Issue:
Breakdown shows "72.75 sSCRT" as the You Get value which includes a 24.25 sSCRT deduction for royalties which only happen on secondary sales.

![image](https://user-images.githubusercontent.com/16178367/139476980-b91298f9-397d-4f15-ac36-5438618c3219.png)

This makes it look like the person creating an NFT will be charged 27.25 sSCRT in fees when they will only be charged 3 sSCRT

## Expected:
The Breakdown not to show a deduction for Royalties for primary listings

## Note(s):
It may make more sense to re-order the page so that Price is shown first, then Royalties underneath with a bit of text that shows the value, then finally show the breakdown like in this shocking paint mockup...

![image](https://user-images.githubusercontent.com/16178367/139478113-2052da02-6880-4789-a2e5-73e69451f937.png)

**Comment by lauraweindorf** [comment]
Verified :tada:

When the creator lists the NFT, there's no reference to royalties. After the NFT has been purchased and the new owner chooses to list it, they see the royalty information.

![image](https://user-images.githubusercontent.com/436905/142784347-90882109-e57e-4f59-9d19-c11b467cf28a.png)
