### ISSUE TITLE
Editing Collection Never Saves 

### ISSUE THREAD

**Issue by Melch18** [SecretChainGirl-Foundation/stashh-QA#120]
Tested in (Chrome): 

## Steps to reproduce
1. Go to 'collection '
2. Click on 'save collection '
3. Collection not "revealed" yet

## Issue:
diamond logo appears trying to save but nothing confirms save, diamond always stays and never navigates back to collection.. 

## Expected:
I expected a green confirmation bubble of collection edited and navigation back to updated collection

**Comment by Melch18** [comment]
Just saw this may be the same issue as @scarylooking 's issue #81

**Comment by scarylooking** [comment]
The Collection update process has been changed since I raised #81, so this looks like something different. Having said that, I am unable to replicate it.

@Melch18  could you try it again and report back if it happens consistently?

**Comment by lauraweindorf** [comment]
I'm not able to reproduce this with the latest release either.
