### ISSUE TITLE
Profile dropdown is not dismissed when Transactions button is clicked

### ISSUE THREAD

**Issue by DanGar2** [SecretChainGirl-Foundation/stashh-QA#144]
When I click on the silhoutte in the top right hand corner a fly out comes out. When I click on the 3 bars after clicking the silhouette another fly out comes out and the original one does not disappear.

**Comment by scarylooking** [comment]
![image](https://user-images.githubusercontent.com/16178367/141650650-70d90942-8d50-4405-a017-6d13de6b4fa7.png)

**Comment by lauraweindorf** [comment]
Verified 🎉
