### ISSUE TITLE
No error message when gas runs out during collection creation

### ISSUE THREAD

**Issue by scarylooking** [SecretChainGirl-Foundation/stashh-QA#150]
Tested in (Chrome, Safari, Edge, Firefox, etc.): 

## Steps to reproduce
1. Go to Create a new Collection
2. Fill out the collection details
3. Click Create
4. Wait for Keplr to pop up a transaction request
5. Select "Low 0.01" gas

![image](https://user-images.githubusercontent.com/16178367/143316794-4be02f06-c366-4cfc-8071-a47eb6e312cd.png)

## Reproducibility
Yes

## Issue:
Transaction fails due to low gas, but does not display an error message to the user and the Create button remains stuck in the "busy" state

## Expected:
An error message to be shown stating that the gas for the txn was too low, and for the create button to be re-enabled.

**Comment by lauraweindorf** [comment]
Verified :tada:
