### ISSUE TITLE
Spam reports fail with an error about viewing keys

### ISSUE THREAD

**Issue by scarylooking** [SecretChainGirl-Foundation/stashh-QA#152]
Tested in (Chrome, Safari, Edge, Firefox, etc.): 

## Steps to reproduce
1. Create a new NFT and navigate to the collection it is in
2. Click the elipsis on the NFT card, then click `spam`
3. On the modal that appears click `submit`

## Reproducibility
Yes

## Issue:
An error appears saying `Please create a viewing key for this collection.`

![image](https://user-images.githubusercontent.com/16178367/143319532-dbe39770-b86b-4f96-b0ee-c118b724dce3.png)

## Expected:
The report to be submitted

**Comment by lauraweindorf** [comment]
Verified :tada:
