### ISSUE TITLE
Should remove tx hash links when waiting for tx to complete until there is a Pulsar-1 explorer

### ISSUE THREAD

**Issue by baedrik** [SecretChainGirl-Foundation/stashh-QA#156]
Tested in (Chrome, Safari, Edge, Firefox, etc.): 

## Issue:
Currently tx hash links send you to secretnodes explorer for supernova-2.  These links should be removed until there is an explorer for pulsar-1

**Comment by lauraweindorf** [comment]
Verified :tada:
