### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kudashovdanila** [SecretChainGirl-Foundation/stashh-QA#169]
Tested in (Chrome, macOS): 

## Steps to reproduce
1. Go to ' http://stashh.io/asset/secret17603pfme4c7qr9madpq77dhpd8v3zdnt49cwvd/1637794430574_4909c'
2. Click on 'Buy now '

## Reproducibility
Yes

## Issue:
Tokens are debited from the account, but there is no NFT

## Expected:
I wanted to buy NFT

**Comment by scarylooking** [comment]
I can't replicate this issue
