### ISSUE TITLE
I am asked to create permit again

### ISSUE THREAD

**Issue by Glu3** [SecretChainGirl-Foundation/stashh-QA#188]
Tested in (Chrome, Safari, Edge, Firefox, etc.): Mac - Chrome

## Steps to reproduce
1. Go to ' My Collection'
2. Click on 'Edit '
3. A pop up shows up asking me to Create Permit

## Reproducibility
Can you make the bug happen again if you repeat the steps above? Yes

## Issue:
I try to edit my Collection and don't understand why I am asked to create Permit

## Expected:
I am the owner of the collection so I should already have the Permit to edit, why I am asked to create permit?

**Comment by scarylooking** [comment]
Possibly related: #188 #179 #186 #183 #191 #190

**Comment by lauraweindorf** [comment]
@LourencoMaltez what was the fix for this one?

**Comment by lauraweindorf** [comment]
Verified it no longer asks user to create a permit from choosing to edit the collection.

:tada:
