### ISSUE TITLE
Always pop up 'Kelpr Transaction Failed' msg.  (Chrome)

### ISSUE THREAD

**Issue by hpzxk** [SecretChainGirl-Foundation/stashh-QA#189]
## Steps to reproduce
1. Goto any NFT page
2. Click 'Buy now'
3. Pop up msg 'Kelpr Transaction Failed', but deduct my balance
![image](https://user-images.githubusercontent.com/14306177/143772763-5a135985-8a32-4bfa-91e1-89b7656a0cd1.png)

(secret1c5yvw0e8xpsdswy6hfs9v2zy403jykgm9k65d8, my address if needed)

## Reproducibility
100%

## Issue:
Always pop up 'Kelpr Transaction Failed' msg.

## Expected:
Transaction should work because my balance is deducted.

**Comment by lauraweindorf** [comment]
Verified :tada:
