### ISSUE TITLE
My collection page shows NFT very unstable.

### ISSUE THREAD

**Issue by hpzxk** [SecretChainGirl-Foundation/stashh-QA#191]
Tested in (Chrome): 

## Steps to reproduce
1. Go to 'My Collections'
2. Click on 'Owned'
3. Check own NFT.
4. Sometimes empty, sometimes 1, sometimes 2.

![00](https://user-images.githubusercontent.com/14306177/143773708-2d39614d-741e-4f80-ac62-e1b60cd0c7fd.jpg)
![01](https://user-images.githubusercontent.com/14306177/143773719-1cca32be-51cc-446c-b1e0-d33850158e2a.jpg)
![02](https://user-images.githubusercontent.com/14306177/143773727-5d16e358-2cb4-4048-8520-da80bef4b946.png)

## Reproducibility
30%

## Issue:
I cant check my own NFTs!

**Comment by scarylooking** [comment]
Possibly related: #188 #179 #186 #183 #191 #190

**Comment by lauraweindorf** [comment]
Verified :tada:
