### ISSUE TITLE
CAN not add token by click  View sSCRT Balance

### ISSUE THREAD

**Issue by liuyingbo** [SecretChainGirl-Foundation/stashh-QA#197]
Tested in (Chrome): 

## Steps to reproduce
1. after get the 100 SCRT
2. Click on ' view sSCRT Balance'
3. ADD token  I can  not submit  
cuz 

i  can not saw the  name ,Symbol,Decimals  
they are all  empty
just contract address is  secret18vd8fpwxzck93qlwghaj6arh4p7c5n8978vsyg

**Comment by liuyingbo** [comment]
[https://media.discordapp.net/attachments/913823778197364776/914822177835089980/20211129133608.png?width=692&height=1115](url)

**Comment by hieu-lai** [comment]
hmm interesting. this seems to be the correct contract address. if it doesnt auto populate, then keplr is having trouble querying the contract.

**Comment by scarylooking** [comment]
Validated that this works. It sometimes take a few moments to populate the details from the contract in Keplr.

Either way, this is a Keplr/network issue rather than something we can fix in Stashh
