### ISSUE TITLE
Transfers always fail

### ISSUE THREAD

**Issue by scarylooking** [SecretChainGirl-Foundation/stashh-QA#199]
Tested in (Chrome, Safari, Edge, Firefox, etc.): 

## Steps to reproduce
1. Create a new single edition NFT
2. Open the asset page for the NFT
3. Click the Transfer button
4. Enter a valid address
5. Click `Transfer`

## Reproducibility
Reproducible every time

## Issue:
An error message is shown saying that the transfer failed.

![image](https://user-images.githubusercontent.com/16178367/144125994-35666524-2fe3-464b-be27-75254fc16a04.png)

Raw log property in the txn response says...

> failed to execute message; message index: 0: encrypted: DQyRiD3kzaAm6V2E7phuxPnz685HryvwB6wCwzmMQmAqtV3ejWv01+y53e+bL+ORGSJL9snJFU2ER0XgThjC9ioMcB8RbTsFk9Tl4+TqkGoNFi1PAMLi/RDJxL726V3MMrHLzva1lQHhkTMDsJvlMQ+gK8A=: execute contract failed

## Expected:
Transfer to succeed

**Comment by lauraweindorf** [comment]
Possibly related to https://github.com/SecretChainGirl-Foundation/stashh-QA/issues/204

But there is no error occurring now.
