### ISSUE TITLE
Collection container is missing an image in display

### ISSUE THREAD

**Issue by lauraweindorf** [SecretChainGirl-Foundation/stashh-QA#203]
### Reproduction Steps

1. Create a collection with > 5 items
2. Click "My Profile"
3. Collection is displayed

### Issue

The last image/item placeholder is not populated with a thumbnail.

![image](https://user-images.githubusercontent.com/436905/144927784-cfffb433-cf75-470e-827b-5aa969c981fe.png)

### Expected Behavior

If there are at least 5 items in the collection, all placeholders should be filled.

### Reproducibility

Yes, every time

### Browser

Chrome

**Comment by hieu-lai** [comment]
fixed

**Comment by jhobsz** [comment]
Verified fix.
