### ISSUE TITLE
Multi Currency Transactions - forgiveness money

### ISSUE THREAD

**Issue by remedycoin** [SecretChainGirl-Foundation/stashh-QA#211]
### Description

At forgiveness capital I am working on creating money based on acts of forgiveness. These are declarative value assets. And rather than achieve market adoption through price negotiations I seek to have these assets become a small part of other transactions. In this way everyone can affirm the infinite value of every human being by accepting 1% of a transaction to be paid with forgiveness-based assets. It would be nice to see this happen with transaction fees as well. This might be useful as a way to discount the fees in the future when the gas fees get outrageous like we see on the Ethereum network.

### Justification

Humans have infinite worth. The scarcity and debt-based monetary systems dishonor this infinite worth unless inside of every transaction there is a component which affirms the infinite value of every human being. Forgiveness-based assets and their cryptocurrencies will provide a way of disarming the harmful effects of scarcity and debt-based transactions. It's pretty good.

**Comment by scarylooking** [comment]
Not a bug. Please don't spam our issues board.
