### ISSUE TITLE
A failed transaction with buying an nft resulted in me losing ssecret[Issue]

### ISSUE THREAD

**Issue by Benb125** [SecretChainGirl-Foundation/stashh-QA#214]
### Reproduction Steps

I bought a dark forest nft
I went back to the screen where it loads and tells you when the payment was successful, and it never loaded and kicked me out.
Then did not give me my ssecret or my nft.

### Issue

I was not given my nft but the ssecret was taken

### Expected Behavior

I was expecting to get my nft

### Reproducibility

Sometimes

### Browser

Chrome

**Comment by scarylooking** [comment]
Hey! If your SCRT has gone then the transaction will have been successful. Sometimes the network doesn't update us.

 If you go to the NFT you bought then click the Refresh button in the top right corner it will show up, or if you go to the Inventory tab in your profile then follow the instructions to create a permit for the collection it will appear

**Comment by Benb125** [comment]
Ok I requested a permit for it and I owned 1 dark forest Nft already and that’s the only one showing up, the other one is still not present and it’s been hours, and I never got returned my ssecret either

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scarylooking** [comment]
Please can you send a transaction hash or wallet address, and the name or ID of the NFT. I'll do some digging and find out what happened

**Comment by Benb125** [comment]
I do not know the exact number that the Nft was but I can send you wallet address and name and ID, would that work, it was in the dark forest collection and there are 300 fairly similar ones.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scarylooking** [comment]
That would be fine. If you don't want to post here please DM me on twitter (StashhApp or ScaryLooking), Telegram (ScaryLooking), or on Discord (ScaryLooking#6601)

**Comment by Benb125** [comment]
So I don’t have the name of the Nft I bought but I know it was a 5 ssecret dark forest one, the exact one didn't really matter to me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Benb125** [comment]
My Wallet address is secret1h4td7m4z0qn3w8c9sal3csv8gpu8acgfn6naff

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Benb125** [comment]
And I have no transaction hash because according to Stashh I never got the Nft and never payed for it but the ssecret left my account

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Benb125** [comment]
24 hours after I received my Nft, I just now got it, thank you for your assistance though

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scarylooking** [comment]
Ah, fab - one of the devs refreshed the collection, so it looks like everything had worked but Stashh had not quite synced up with the blockchain
